version: '3'
services:

  postgres:
    image: 'postgres:14.1-alpine'
    container_name: postgres_container
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
      PGDATA: '/data/postgres'
    ports:
      - '5432:5432'
    volumes:
      - ./temp/postgresql:/var/lib/postgresql/data
    networks:
      - minha-rede

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'user@domain.com'
      PGADMIN_DEFAULT_PASSWORD: 'SuperSecret'
    depends_on:
        - postgres
    ports:
      - '90:80'
    volumes:
      - ./temp/pgadmin4:/var/lib/pgadmin4/data
    networks:
      - minha-rede

  redis:
    image: redis:6.2-alpine
    container_name: redis_container
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - ./temp/redis:/data

volumes:
  db:
    driver: local

networks:
  minha-rede:
    driver: bridge
