version: '3'
services:

  postgres:
    image: 'postgres:14.1-alpine'
    container_name: postgres_container
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
      PGDATA: '/data/postgres'
    ports:
      - '5433:5432'
    volumes:
      - ./temp/postgresql:/var/lib/postgresql/data
    networks:
      - minha-rede

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'user@domain.com'
      PGADMIN_DEFAULT_PASSWORD: 'SuperSecret'
    depends_on:
        - postgres
    ports:
      - '90:80'
    volumes:
      - ./temp/pgadmin4:/var/lib/pgadmin4/data
    networks:
      - minha-rede

  nestjs:
    build:
      context: ..
      dockerfile: Dockerfile
    image: nestjs
    depends_on:
        - postgres
    container_name: nestjs_container
    ports:
      - '3000:3000'
    restart: unless-stopped
    networks:
      - minha-rede

  certbot:
    image: certbot/certbot:latest
    container_name: certbot_container
    depends_on:
        - nestjs
   
    volumes:
      - ./temp/certbot/letsencrypt/:/etc/letsencrypt
      - ./temp/certbot/www/:/var/www/certbot
      - ./temp/certbot/web-root:/var/www/html
    command: certonly --webroot -w /var/www/certbot --force-renewal --email admin@eixoxprojetos.com.br -d dotatryhard.eixoxprojetos.com.br --agree-tos
    networks:
      - minha-rede

  nginx:
      image: nginx:latest
      container_name: nginx_container
      ports:
        - 80:80
        - 443:443
      restart: always
      depends_on:
        - certbot
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/server:/etc/nginx/sites-enabled/server
        - ./nginx/server:/etc/nginx/sites-available/server
        - ./temp/certbot/letsencrypt/:/etc/letsencrypt
        - ./temp/certbot/www/:/var/www/certbot
      networks:
        - minha-rede
volumes:
  db:
    driver: local

networks:
  minha-rede:
    driver: bridge
